version: 2.1

executors:
  ruby:
    docker:
      - image: ruby:3.0.0
      - image: postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres

workflows:
  run-tests:
    jobs:
      - test-ruby:
          name: ruby-unit-tests

jobs:
  test-ruby:
    executor: ruby
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: bundler install
      - run:
          name: Migrate DB
          command: rake db:migrate
      - run:
          name: Run tests
          command: rspec --format documentation
