version: 2.1

executors:
  ruby:
    docker:
      - image: ruby:3.0.0
      - image: postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
  docker-in-docker:
    docker:
      - image: docker:18.06.1-ce

workflows:
  run-tests:
    jobs:
      # - test-ruby:
      #     name: ruby-unit-tests
      - deploy-ruby:
          name: deploy-aws
          # requires:
          #   - ruby-unit-tests
          # filters:
          #   branches:
          #     only: master

jobs:
  test-ruby:
    executor: ruby
    steps:
      - checkout
      - run: 
          name: Install dependencies
          command: bundler install
      - run:
          name: Setup and migrate DB
          command: |
            rake db:create
            rake db:migrate
      - run:
          name: Run tests
          command: rspec --format documentation

  deploy-ruby:
    executor: docker-in-docker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build docker image
          command: |
            docker build . -t stevensim226/minisocial-be
            echo $DOCKER_TOKEN | docker login -u $DOCKER_USERNAME --password-stdin
            docker push stevensim226/minisocial-be:latest
      - run:
          name: Run shell script
          command: |
            apk add openssh-client
            pwd
            ls
            echo $SSH_KEY > ~/.ssh/line_key
            LF=$'\\\x0A'
            cat ~/.ssh/line_key \
              | sed -e "s/-----BEGIN RSA PRIVATE KEY-----/&${LF}/" -e "s/-----END RSA PRIVATE KEY-----/${LF}&${LF}/" \
              | fold -w 64 > .priv_key

            chmod 400 ~/.ssh/.priv_key
            ssh -i ~/.ssh/.priv_key ubuntu@$EC2_IP < .circleci/deploy_ec2.sh
      
